Traceback (most recent call last):
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/jordivilla/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jordivilla/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
iris = iris.drop(index='Unnamed:0')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m iris [38;5;241m=[39m [43miris[49m[38;5;241;43m.[39;49m[43mdrop[49m[43m([49m[43mindex[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mUnnamed:0[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/pandas/core/frame.py:5258[0m, in [0;36mDataFrame.drop[0;34m(self, labels, axis, index, columns, level, inplace, errors)[0m
[1;32m   5110[0m [38;5;28;01mdef[39;00m [38;5;21mdrop[39m(
[1;32m   5111[0m     [38;5;28mself[39m,
[1;32m   5112[0m     labels: IndexLabel [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m   5119[0m     errors: IgnoreRaise [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m,
[1;32m   5120[0m ) [38;5;241m-[39m[38;5;241m>[39m DataFrame [38;5;241m|[39m [38;5;28;01mNone[39;00m:
[1;32m   5121[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   5122[0m [38;5;124;03m    Drop specified labels from rows or columns.[39;00m
[1;32m   5123[0m 
[0;32m   (...)[0m
[1;32m   5256[0m [38;5;124;03m            weight  1.0     0.8[39;00m
[1;32m   5257[0m [38;5;124;03m    """[39;00m
[0;32m-> 5258[0m     [38;5;28;01mreturn[39;00m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mdrop[49m[43m([49m
[1;32m   5259[0m [43m        [49m[43mlabels[49m[38;5;241;43m=[39;49m[43mlabels[49m[43m,[49m
[1;32m   5260[0m [43m        [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m,[49m
[1;32m   5261[0m [43m        [49m[43mindex[49m[38;5;241;43m=[39;49m[43mindex[49m[43m,[49m
[1;32m   5262[0m [43m        [49m[43mcolumns[49m[38;5;241;43m=[39;49m[43mcolumns[49m[43m,[49m
[1;32m   5263[0m [43m        [49m[43mlevel[49m[38;5;241;43m=[39;49m[43mlevel[49m[43m,[49m
[1;32m   5264[0m [43m        [49m[43minplace[49m[38;5;241;43m=[39;49m[43minplace[49m[43m,[49m
[1;32m   5265[0m [43m        [49m[43merrors[49m[38;5;241;43m=[39;49m[43merrors[49m[43m,[49m
[1;32m   5266[0m [43m    [49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/pandas/core/generic.py:4549[0m, in [0;36mNDFrame.drop[0;34m(self, labels, axis, index, columns, level, inplace, errors)[0m
[1;32m   4547[0m [38;5;28;01mfor[39;00m axis, labels [38;5;129;01min[39;00m axes[38;5;241m.[39mitems():
[1;32m   4548[0m     [38;5;28;01mif[39;00m labels [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m-> 4549[0m         obj [38;5;241m=[39m [43mobj[49m[38;5;241;43m.[39;49m[43m_drop_axis[49m[43m([49m[43mlabels[49m[43m,[49m[43m [49m[43maxis[49m[43m,[49m[43m [49m[43mlevel[49m[38;5;241;43m=[39;49m[43mlevel[49m[43m,[49m[43m [49m[43merrors[49m[38;5;241;43m=[39;49m[43merrors[49m[43m)[49m
[1;32m   4551[0m [38;5;28;01mif[39;00m inplace:
[1;32m   4552[0m     [38;5;28mself[39m[38;5;241m.[39m_update_inplace(obj)

File [0;32m~/.local/lib/python3.10/site-packages/pandas/core/generic.py:4591[0m, in [0;36mNDFrame._drop_axis[0;34m(self, labels, axis, level, errors, only_slice)[0m
[1;32m   4589[0m         new_axis [38;5;241m=[39m axis[38;5;241m.[39mdrop(labels, level[38;5;241m=[39mlevel, errors[38;5;241m=[39merrors)
[1;32m   4590[0m     [38;5;28;01melse[39;00m:
[0;32m-> 4591[0m         new_axis [38;5;241m=[39m [43maxis[49m[38;5;241;43m.[39;49m[43mdrop[49m[43m([49m[43mlabels[49m[43m,[49m[43m [49m[43merrors[49m[38;5;241;43m=[39;49m[43merrors[49m[43m)[49m
[1;32m   4592[0m     indexer [38;5;241m=[39m axis[38;5;241m.[39mget_indexer(new_axis)
[1;32m   4594[0m [38;5;66;03m# Case for non-unique axis[39;00m
[1;32m   4595[0m [38;5;28;01melse[39;00m:

File [0;32m~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py:6696[0m, in [0;36mIndex.drop[0;34m(self, labels, errors)[0m
[1;32m   6694[0m [38;5;28;01mif[39;00m mask[38;5;241m.[39many():
[1;32m   6695[0m     [38;5;28;01mif[39;00m errors [38;5;241m!=[39m [38;5;124m"[39m[38;5;124mignore[39m[38;5;124m"[39m:
[0;32m-> 6696[0m         [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mlist[39m(labels[mask])[38;5;132;01m}[39;00m[38;5;124m not found in axis[39m[38;5;124m"[39m)
[1;32m   6697[0m     indexer [38;5;241m=[39m indexer[[38;5;241m~[39mmask]
[1;32m   6698[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mdelete(indexer)

[0;31mKeyError[0m: "['Unnamed:0'] not found in axis"
KeyError: "['Unnamed:0'] not found in axis"

